
debug: true

logging:
  level:
    httpclient:
      wire: DEBUG
    org:
      springframework:
        web:
          servlet.DispatcherServlet: DEBUG
          client.RestTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

secret:
  api:
    key: ${API_KEY}

aws:
  bucket:
    name: ${ACCESS_KEY}
  accessKey: ${SECRET_KEY}
  secretKey: ${BUCKET_NAME}
